// 執行：node F3/wood-bridge.test.cjs
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const html = fs.readFileSync(`${__dirname}/wood-bridge.html`, 'utf8');
const source = html.match(/<script id="bridge-model">([\s\S]*?)<\/script>/)[1];
// 測試碎段拓撲時直接指定切口；承重觸發斷裂另由超載測試驗證。
const testSource=source.replace('return {UNIT,DT','return {cutAt(sim,index,t=.5){breakBar(sim,sim.bars[index],Math.round(t*(sim.bars[index].path.length-1)));rebuildConstraints(sim);},UNIT,DT');
const B = new Function(`${testSource}\nreturn Bridge;`)();
const inputSource = html.match(/\/\/ 指標幾何開始[^\n]*\n([\s\S]*?)\/\/ 指標幾何結束/)[1];
const input = vm.runInNewContext(`${inputSource}\n({snap,buildPoint,isDrag})`,{Bridge:B});
const snapDesign=B.empty();B.addBar(snapDesign,{x:6,y:8},{x:16,y:8});
const snapped=input.buildPoint({x:8.73,y:7.9},snapDesign);
assert.ok(snapped.x===8.5 && snapped.y===8,'先對齊 5 cm 方格，再吸附桿身');
assert.ok(input.buildPoint({x:8.52,y:7.85},snapDesign).x===snapped.x,'同一方格內移動不應在桿身任意滑動');
assert.ok(Math.abs(input.buildPoint({x:6.5,y:8},snapDesign).x-6.5)<1e-10,'相鄰 5 cm 落點不能被端點吸回');
const gridFallback=input.buildPoint({x:10.2,y:3.1},snapDesign);
assert.ok(gridFallback.x===10 && gridFallback.y===3,'空白位置保持方格吸附');
const slopeSnap=B.empty();B.addBar(slopeSnap,{x:6,y:4},{x:10,y:6});
const slopePoint=input.buildPoint({x:8.18,y:5.215},slopeSnap);
assert.ok(slopePoint.x===8 && slopePoint.y===5,'斜桿使用方格位置的垂直投影');
const shiftedRail=B.empty();B.addBar(shiftedRail,{x:6,y:7.94},{x:16,y:7.94});
const railPoint=input.buildPoint({x:8.73,y:7.9},shiftedRail);
assert.ok(railPoint.x===8.5 && Math.abs(railPoint.y-7.94)<1e-10,'不在方格上的木桿仍保持貼合，不把木桿本身移回方格');
assert.ok(Math.abs(input.buildPoint({x:8.73,y:8.2},shiftedRail).y-7.94)<1e-10,'方格落點靠近木桿時也須吸附');
const offGridSlope=B.empty();B.addBar(offGridSlope,{x:6,y:3.52},{x:10,y:7.52});
const alongSlope=input.buildPoint({x:8.24,y:5.76},offGridSlope);
assert.ok(Math.abs(alongSlope.y-alongSlope.x+2.48)<1e-10,'滑鼠沿斜桿移動時，不能因方格較遠而脫離桿身');
const endpointSnap=B.empty();B.addBar(endpointSnap,{x:6.13,y:3.27},{x:9.13,y:3.27});
const offGridEndpoint=input.buildPoint({x:6.17,y:3.23},endpointSnap);
assert.equal(B.addBar(endpointSnap,offGridEndpoint,{x:6,y:1}),'');
assert.equal(endpointSnap.bars[1].a,endpointSnap.bars[0].a,'接近不在方格上的端點時仍須共用同一節點');
const farEnd=input.buildPoint({x:9.08,y:3.23},endpointSnap);
assert.ok(farEnd.x===9.13 && farEnd.y===3.27,'同一條木桿的另一端也須精確吸附');
const crossingSnap=B.empty();B.addBar(crossingSnap,{x:8.13,y:3.1},{x:8.13,y:5.1});B.addBar(crossingSnap,{x:6,y:5},{x:10,y:5});
const crossingEnd=input.buildPoint({x:8.1,y:5},crossingSnap);
assert.ok(crossingEnd.x===8.13 && crossingEnd.y===5.1,'附近端點不能被更接近滑鼠的另一條木桿遮蔽');
const snapPlaced=B.clone(snapDesign);
assert.equal(B.addBar(snapPlaced,{x:8.73,y:6},snapped),'');
assert.equal(snapPlaced.joints.length,0,'吸附桿身只決定位置，不自動接合');
assert.equal(B.connectTouching(snapPlaced,snapped),1,'吸附後按「接合」才連接桿身');
const snapEdited=B.clone(snapDesign);B.addBar(snapEdited,{x:8.73,y:6},{x:8.73,y:7});
const editedTip=snapEdited.bars[1].b;
assert.equal(input.buildPoint({x:8.73,y:6.8},snapEdited,editedTip).x,8.5,'拖動端點不吸附自己的相連木桿');
const editSnap=input.buildPoint({x:8.73,y:7.9},snapEdited,editedTip);
assert.equal(B.moveNode(snapEdited,editedTip,editSnap),'');
assert.ok(snapEdited.nodes[editedTip].x===8.5 && snapEdited.nodes[editedTip].y===8,'拖動修改採用相同的方格與桿身吸附');
assert.equal(snapEdited.joints.length,0,'修改吸附不會繞過接合確認');
const endJoined=B.empty();
B.addBar(endJoined,{x:6,y:4},{x:9,y:4});B.addBar(endJoined,{x:10.13,y:4},{x:14,y:4});
endJoined.nodes[1].load=2;endJoined.nodes[2].load=3;
const endLoad=B.placeLoad(endJoined,null,0,.5,1);
const endPoint=input.buildPoint({x:10.17,y:4.03},endJoined,1);
assert.equal(B.moveNode(endJoined,1,endPoint),'','端點可吸附不在方格上的另一木桿末端');
assert.equal(endJoined.nodes[1].x,10.13);assert.equal(endJoined.nodes[2].x,10.13,'目標端點保持原位');
assert.equal(endJoined.joints.length,1,'同一直線末端亦會自動接合');
assert.equal(endJoined.joints[0].kind,'pin','末端接合容許木桿相對轉動');
assert.equal(endJoined.nodes.reduce((sum,n)=>sum+n.load,0),6,'兩端及中段負重均保留');
assert.ok(B.distance(endJoined.nodes[endLoad],B.barPoint(endJoined,0,.5))<1e-10);
assert.equal(B.moveNode(endJoined,1,{x:10.13,y:3.5}),'','接合後仍可調整端點');
assert.ok(B.distance(endJoined.nodes[1],endJoined.nodes[2])<1e-6,'再次修改會帶動相連末端');
assert.equal(endJoined.joints.length,1,'再次修改不重複建立接點');
const endSim=B.simulate(endJoined);B.step(endSim);
assert.ok(B.distance(endSim.nodes[1],endSim.nodes[2])<1e-5,'測試時末端持續相連');
const endSaved=JSON.stringify(endJoined);
assert.ok(B.moveNode(endJoined,1,endJoined.nodes[0]),'不可把木桿壓成零長度');
assert.equal(JSON.stringify(endJoined),endSaved,'無效末端接合不可留下部分修改');
const detachedEnd=B.clone(endJoined);detachedEnd.joints=[];
B.addBar(detachedEnd,{x:6,y:7},{x:8,y:7});
assert.equal(B.moveNode(detachedEnd,detachedEnd.bars.at(-1).b,{x:8.5,y:7}),'');
assert.equal(detachedEnd.joints.length,0,'修改別處不會重新接上已解除的端點接合');
const a={x:6,y:8}, b={x:6.5,y:8};
assert.equal(B.distance(input.snap(a),input.snap(b)),.5,'相鄰 5 cm 方格不能吸回原節點');
assert.ok(input.isDrag(a,b,349),'手機畫布必須接受一格 5 cm 的短拖拉');
assert.ok(!input.isDrag(a,{x:6.05,y:8},349),'輕微點按位移不當作拖拉');
const run = (design,seconds=3) => {
  const sim=B.simulate(design);
  for(let i=0;i<seconds/B.DT;i++) B.step(sim);
  for(const node of sim.nodes) assert.ok([node.x,node.y,node.vx,node.vy].every(Number.isFinite),'模擬數值必須保持有限');
  return sim;
};
const design=B.sample(), original=JSON.stringify(design), center=design.nodes.findIndex(n=>n.load);
const materialTotal=design=>B.materialRows(design).reduce((sum,row)=>sum+row.total,0)/100;
const assertMaterialTotal=design=>assert.ok(Math.abs(materialTotal(design)-B.totalLength(design))<1e-10,'材料表合計必須等於木材總長度');
assert.deepEqual(B.materialRows(B.empty()),[],'空白設計的材料表應為空');
assert.equal(design.bars.length,18,'預設橋應包含 18 條木桿');
assert.ok(Math.abs(B.totalLength(design)-5.155342607214207)<1e-12,'預設橋單面木材總長度正確');
const sampleRows=B.materialRows(design);
assert.deepEqual(sampleRows.map(row=>[row.kind,row.count]),[[0,2],[1,1],[2,7],[3,2],[3,6]],'材料表應按底、頂、直、斜分類');
assert.ok(Math.abs(sampleRows[0].length-100)<1e-10 && Math.abs(sampleRows[1].length-80)<1e-10,'底梁及頂梁長度正確');
assert.ok(Math.abs(sampleRows[2].length-13)<1e-10 && Math.abs(sampleRows[3].length-Math.hypot(10,13))<1e-10 && Math.abs(sampleRows[4].length-Math.hypot(80/6,13))<1e-10,'直桿及斜桿長度正確');
assertMaterialTotal(design);
const tableDesign=B.clone(design), reinforcedRows=JSON.stringify(B.materialRows(tableDesign));
assert.equal(B.reinforce(tableDesign,2),'','材料表測試可加固木桿');
assert.notEqual(JSON.stringify(B.materialRows(tableDesign)),reinforcedRows,'加固後材料表應更新');
assert.equal(B.materialRows(tableDesign).find(row=>row.kind===1 && Math.abs(row.length-80)<1e-10).count,2,'加固頂梁後材料表數量應為 2');
assertMaterialTotal(tableDesign);
const editTable=B.empty();
assert.equal(B.addBar(editTable,{x:6,y:8},{x:8,y:8}),'');
assert.equal(B.materialRows(editTable)[0].length,20,'修改前材料表應記錄 20 cm');
assert.equal(B.moveNode(editTable,editTable.bars[0].b,{x:9,y:8}),'','材料表測試可修改木桿端點');
assert.ok(Math.abs(B.materialRows(editTable)[0].length-30)<1e-10,'修改後材料表應更新為 30 cm');
assert.ok(Math.abs(B.materialRows(editTable)[0].total-30)<1e-10,'修改後材料表合計應更新');
assertMaterialTotal(editTable);
const beforeRemove=B.totalLength(tableDesign), removedLength=tableDesign.bars[0].length*B.UNIT, removedRows=JSON.stringify(B.materialRows(tableDesign));
B.removeBar(tableDesign,0);
assert.notEqual(JSON.stringify(B.materialRows(tableDesign)),removedRows,'刪除後材料表應更新');
assert.ok(Math.abs(B.totalLength(tableDesign)-(beforeRemove-removedLength))<1e-10,'刪除後木材總長度應扣除被刪木桿');
assertMaterialTotal(tableDesign);
const ramp=B.simulate(design);
const firstIncrement=B.increaseLoad(ramp,center);
assert.ok(Math.abs(firstIncrement-2-.5*B.DT)<1e-12,'每個時間步即按 0.5 kg/s 加重');
for(let i=1;i<1/B.DT;i++) B.increaseLoad(ramp,center);
assert.ok(Math.abs(ramp.nodes[center].load-2.5)<1e-8,'連續加重速率為每秒 0.5 kg');
ramp.nodes[center].load=19.99999;
assert.equal(B.increaseLoad(ramp,center),20,'連續加重不得超過 20 kg');
ramp.nodes[center].load=3.14159;ramp.firstBreak={bar:0,load:3.14159};
assert.equal(B.increaseLoad(ramp,center),3.14159,'首次斷裂後停止加重並保留精確負重');
assert.ok(Math.abs((B.RIGHT_EDGE-B.LEFT_EDGE)*B.UNIT-.95)<1e-10,'河口淨距應為 95 cm');
assert.ok(design.nodes.every(n=>!n.fixed),'所有節點均不得固定');
assert.equal(B.empty().nodes.length,0,'清空後不能留下固定支點');
const lifted=B.simulate(design);
for(const n of lifted.nodes) {n.vx=2;n.vy=-2;}
B.step(lifted);
assert.ok(lifted.nodes[0].x>design.nodes[0].x && lifted.nodes[0].y<design.nodes[0].y,'橋腳必須能水平移動及向上離地');
const long=B.empty();
assert.equal(B.addBar(long,{x:5,y:8},{x:15,y:8}),'','允許 100 cm 木桿');
assert.equal(long.bars[0].length*B.UNIT*100,100);
assert.ok(B.addBar(long,{x:5,y:8},{x:15.5,y:8}),'拒絕超過 100 cm 木桿');
assert.equal(B.barAt(long,{x:10,y:8},.2),0,'按桿身應找到木桿');
assert.equal(B.barAt(long,{x:10,y:7},.2),-1,'空白位置不能誤選木桿');
const central=B.empty();assert.equal(B.addBar(central,{x:6,y:7},{x:15,y:5}),'');
assert.equal(B.CENTER_X,(B.LEFT_EDGE+B.RIGHT_EDGE)/2,'中央線必須由兩岸位置決定');
assert.equal(B.loadHit(central,{x:8,y:6.6},.3),null,'不能在中央線以外的桿身掛重物');
const centralHit=B.loadHit(central,{x:12.1,y:5.8},.3);
assert.ok(centralHit && Math.abs(centralHit.t-2/3)<1e-10,'斜桿必須使用與中央線的真正交點，不能用木桿中點或垂直投影');
const centralLoad=B.placeLoad(central,null,centralHit.bar,centralHit.t,1);
assert.equal(central.nodes[centralLoad].x,B.CENTER_X,'點按容差不能使掛點偏離中央線');
const beside=B.empty();B.addBar(beside,{x:9,y:5},{x:11.99,y:5});
assert.equal(B.loadHit(beside,{x:12,y:5},.3),null,'接近中央線但未跨過的木桿不能承接中央負重');
const vertical=B.empty();B.addBar(vertical,{x:12,y:3},{x:12,y:7});
const verticalHit=B.loadHit(vertical,{x:12.1,y:5.3},.3);
assert.ok(verticalHit && Math.abs(B.barPoint(vertical,0,verticalHit.t).y-5.3)<1e-10,'中央線上的直桿可按高度掛重物');
const awayVertical=B.empty();B.addBar(awayVertical,{x:11.9,y:3},{x:11.9,y:7});
assert.equal(B.loadHit(awayVertical,{x:12,y:5},.3),null,'旁邊的平行直桿不能吸附成中央掛點');
const movingCenter=B.simulate(central);
movingCenter.nodes.forEach(n=>n.x+=.002);
assert.ok(B.canAddLoad(movingCenter.nodes[centralLoad]),'掛好後離開中央線的重物仍可調整重量');
const newCenterHit=B.loadHit(movingCenter,{x:12,y:5.8},.3);
const nextCentralLoad=B.placeLoad(central,movingCenter,newCenterHit.bar,newCenterHit.t,1);
assert.notEqual(nextCentralLoad,centralLoad,'不能重用附近已離開中央線的掛點來新增中央負重');
assert.ok(Math.abs(movingCenter.nodes[nextCentralLoad].x-B.CENTER_X)<1e-8);
movingCenter.nodes[centralLoad].load=0;
assert.ok(!B.canAddLoad(movingCenter.nodes[centralLoad]),'卸下後不能在已離開中央線的位置重新掛上');
assert.equal(B.increaseLoad(movingCenter,centralLoad),0,'連續加重不能繞過重新掛上的位置限制');
assert.ok(B.increaseLoad(movingCenter,nextCentralLoad)>1,'已有中央負重仍可連續加重');
const deformed=B.simulate(long);deformed.nodes[1].x=16;
assert.equal(B.barAt(deformed,{x:15.9,y:8},.2),0,'變形後須以目前幾何選取木桿');
assert.equal(deformed.bars[0].length*B.UNIT*100,100,'量度原長不應被變形改寫');
assert.equal(design.bars.length,18);
const lightlyLoaded=B.clone(design);lightlyLoaded.nodes[center].load=.2;
const loaded=run(lightlyLoaded);
assert.equal(JSON.stringify(design),original,'測試不可改寫設計');
assert.deepEqual(lightlyLoaded,{...design,nodes:design.nodes.map((n,i)=>i===center?{...n,load:.2}:n)},'小負重測試不可改寫設計');
assert.equal(loaded.bars.filter(b=>b.broken).length,0,'輕木範例應能承受 0.2 kg 小負重');
assert.ok(loaded.nodes[center].y>8,'重物應拉低橋身');
assert.ok(loaded.nodes[center].y<8.5,'三角桁架應維持形狀');
const unloaded=B.clone(design);unloaded.nodes[center].load=0;
assert.ok(run(unloaded).nodes[center].y<loaded.nodes[center].y,'加重應增加下移');
const overloaded=B.clone(design);overloaded.nodes[center].load=20;
const destroyed=run(overloaded);
assert.ok(destroyed.bars.some(b=>b.broken),'超載應造成木桿斷裂');
assert.equal(destroyed.fragments.length,destroyed.bars.filter(b=>b.broken).length*2,'每條斷桿產生兩段木材');
assert.equal(destroyed.firstBreak.load,20,'記錄第一次斷裂的總負重');
const fractured=B.simulate(long), massBefore=fractured.nodes.reduce((sum,n)=>sum+n.baseMass,0);
B.cutAt(fractured,0);
assert.equal(fractured.fragments.length,2);
assert.notEqual(fractured.fragments[0].b,fractured.fragments[1].b,'兩個斷口不能共用節點');
assert.ok(Math.abs(fractured.nodes.reduce((sum,n)=>sum+n.baseMass,0)-massBefore)<1e-10,'斷裂前後質量守恆');
const shifted=B.clone(fractured), right=shifted.fragments[1];
shifted.nodes[right.a].x+=1;shifted.nodes[right.b].x+=1;
B.step(fractured);B.step(shifted);
assert.equal(shifted.nodes[0].fx,fractured.nodes[0].fx,'移動右半段不能透過斷口把力傳到左半段');
const tip=fractured.nodes[fractured.fragments[0].b], tipY=tip.y;
for(let i=0;i<.1/B.DT;i++) B.step(fractured);
assert.notEqual(tip.y,tipY,'斷口必須受力移動');
const changed=B.empty();
B.addBar(changed,{x:6,y:8},{x:12,y:8});
B.addBar(changed,{x:12,y:8},{x:18,y:8});
B.addBar(changed,{x:12,y:8},{x:12,y:5});
const changedCenter=changed.nodes.findIndex(n=>n.x===12&&n.y===8);
changed.nodes[changedCenter].load=2;
const changedOriginal=JSON.stringify(changed), originalNode=B.clone(changed.nodes[changedCenter]);
const incident=changed.bars.filter(bar=>bar.a===changedCenter||bar.b===changedCenter);
assert.equal(B.moveNode(changed,changedCenter,{x:12,y:7.5}),'');
assert.equal(changed.nodes[changedCenter].load,originalNode.load,'修改端點保留負重');
assert.ok(incident.every(bar=>Math.abs(bar.length-B.distance(changed.nodes[bar.a],changed.nodes[bar.b]))<1e-10),'相連木桿長度全部更新');
const saved=JSON.stringify(changed);
assert.ok(B.moveNode(changed,changedCenter,{x:6,y:8}),'不把相連木桿縮成零長度');
assert.ok(B.moveNode(changed,changedCenter,{x:4,y:1}),'相連木桿超長時拒絕修改');
assert.ok(B.moveNode(changed,changedCenter,{x:6,y:9}),'不能移到岸面以下');
assert.equal(JSON.stringify(changed),saved,'無效修改不能部分改寫設計');
assert.equal(B.moveNode(changed,changedCenter,{x:originalNode.x,y:originalNode.y}),'');
assert.equal(JSON.stringify(changed),changedOriginal,'可還原原來端點及木桿長度');
const flat=B.empty();
for(let x=6;x<18;x+=3) assert.equal(B.addBar(flat,{x,y:8},{x:x+3,y:8}),'');
flat.nodes.find(n=>n.x===12).load=2;
assert.ok(run(flat).nodes.find(n=>n.load).y>loaded.nodes[center].y+.2,'無斜撐的橋應有較大下移');
const before=JSON.stringify(flat);
assert.ok(B.addBar(flat,{x:6,y:8},{x:9,y:8}),'拒絕重複木桿');
assert.ok(B.addBar(flat,{x:4,y:8},{x:4,y:8}),'拒絕零長度');
assert.ok(B.addBar(flat,{x:4,y:8},{x:20,y:8}),'拒絕過長木桿');
assert.ok(B.addBar(flat,{x:NaN,y:8},{x:8,y:8}),'拒絕無效座標');
assert.ok(B.addBar(flat,{x:6,y:8},{x:6,y:9}),'拒絕埋入地面的端點');
assert.equal(JSON.stringify(flat),before,'無效操作不應新增端點');
const short=B.empty();B.addBar(short,{x:6,y:8},{x:6,y:7.5});run(short);
const tinyFragments=B.simulate(short);B.cutAt(tinyFragments,0);
for(let i=0;i<1/B.DT;i++) B.step(tinyFragments);
assert.equal(tinyFragments.fragments.length,2);
assert.ok(tinyFragments.nodes.every(n=>[n.x,n.y,n.vx,n.vy].every(Number.isFinite)),'最短木桿斷裂後也須穩定');
const loose=B.empty();B.addBar(loose,{x:4,y:6},{x:5,y:6});
assert.ok(run(loose).nodes.every(n=>n.y<=B.GROUND),'岸上節點應由地面承托');
const slipping=B.simulate(short);
for(const n of slipping.nodes) n.vx=20;
for(let i=0;i<.2/B.DT;i++) B.step(slipping);
assert.ok(slipping.nodes[0].x>B.LEFT_EDGE && slipping.nodes[0].y>B.GROUND,'橋腳能滑出岸邊後下墜');
B.removeBar(flat,0);
assert.ok(flat.bars.every(b=>flat.nodes[b.a]&&flat.nodes[b.b]),'移除後端點索引應有效');
while(flat.bars.length) B.removeBar(flat,0);
assert.equal(flat.nodes.length,0,'移除全部木桿後不保留孤立節點');
const stock=B.empty();
for(let i=0;i<20;i++) {
  const x=4+(i%10)*.5,y=1+Math.floor(i/10)*.5;
  assert.equal(B.addBar(stock,{x,y},{x:x+10,y}),'');
}
assert.equal(B.totalLength(stock),20,'剛好 20 m 可以建造');
const fullStock=JSON.stringify(stock);
assert.ok(B.addBar(stock,{x:6,y:8},{x:6.5,y:8}),'總長超過 20 m 時拒絕新增');
assert.equal(JSON.stringify(stock),fullStock,'超額新增不能留下節點');
assert.equal(B.moveNode(stock,stock.bars[0].b,{x:13.5,y:1}),'');
assert.equal(B.addBar(stock,{x:6,y:8},{x:6.5,y:8}),'','縮短後可用回剩餘木材');
const exactStock=JSON.stringify(stock);
assert.ok(B.moveNode(stock,stock.bars.at(-1).b,{x:7,y:8}),'拖動後總長不可超過 20 m');
assert.equal(JSON.stringify(stock),exactStock,'超額拖動必須完整還原');
B.removeBar(stock,1);assert.ok(B.totalLength(stock)<20,'刪除木桿退回可用長度');

const tee=B.empty();
B.addBar(tee,{x:6,y:6},{x:14,y:6});
B.addBar(tee,{x:10,y:6},{x:10,y:4});
assert.equal(tee.joints.length,0,'端點碰到桿身不自動接合');
const teeLength=B.totalLength(tee);
assert.equal(B.connectTouching(tee,{x:10,y:6}),1,'可確認端點到中段的接合');
assert.equal(B.connectTouching(tee,{x:10,y:6}),0,'同一接合不重複新增');
assert.equal(tee.bars.length,2,'中段接合不把整條木材切成鉸接短桿');
assert.equal(B.totalLength(tee),teeLength,'接合不消耗或退回木材');
const teeSim=B.simulate(tee), unjoined=B.clone(tee);unjoined.joints=[];
const noJoint=B.simulate(unjoined), branch=tee.bars[1];
teeSim.nodes[branch.a].y-=.02;noJoint.nodes[branch.a].y-=.02;
B.step(teeSim);B.step(noJoint);
const teeMid=teeSim.bars[0].path[(teeSim.bars[0].path.length-1)/2];
assert.ok(teeSim.nodes[teeMid].fy<noJoint.nodes[teeMid].fy,'中段接合須向長木桿的對應位置傳力');
const rotated=B.simulate(tee);
for(const i of rotated.bars[1].path) {const n=rotated.nodes[i],y=n.y;n.x=10+6-y;n.y=6;}
B.step(rotated);
assert.ok(rotated.nodes.every(n=>Math.abs(n.fx)<1e-8),'單點接合容許木桿轉動');
const editedTee=B.clone(tee);
assert.equal(B.moveNode(editedTee,tee.bars[0].a,{x:6,y:5.5}),'');
const teeJoint=editedTee.joints[0].links[0];
assert.ok(B.distance(B.barPoint(editedTee,0,teeJoint.ta),B.barPoint(editedTee,1,teeJoint.tb))<1e-5,'修改長桿時維持中段接合');
run(tee,1);

const crossing=B.empty();
B.addBar(crossing,{x:6,y:4},{x:10,y:8});B.addBar(crossing,{x:6,y:8},{x:10,y:4});
assert.equal(B.connectTouching(crossing,{x:6,y:6},.2),0,'空白位置不會接合附近木桿');
assert.equal(B.connectTouching(crossing,{x:8,y:6},.2),1,'交叉處可以接合');
const parallel=B.empty();
B.addBar(parallel,{x:6,y:3},{x:10,y:3});B.addBar(parallel,{x:7,y:3.5},{x:11,y:3.5});
const beforeGlue=B.totalLength(parallel);
assert.equal(B.glueBars(parallel,0,1),'');
assert.equal(B.totalLength(parallel),beforeGlue,'膠合時仍計算兩條木材的完整用量');
assert.ok(B.glueBars(parallel,0,1),'不可重複膠合');
const glued=B.simulate(parallel), second=glued.bars[1], mid=B.barPoint(glued,1,.5);
for(const i of second.path) {
  const x=glued.nodes[i].x-mid.x;
  glued.nodes[i].x=mid.x+x*Math.cos(.03);glued.nodes[i].y=mid.y+x*Math.sin(.03);
}
B.step(glued);
const torque=(glued.nodes[second.b].x-mid.x)*glued.nodes[second.b].fy+(glued.nodes[second.a].x-mid.x)*glued.nodes[second.a].fy;
assert.ok(torque<0,'膠合須產生抵抗相對轉動的力矩');
for(let i=0;i<.1/B.DT;i++) B.step(glued);
assert.ok(glued.nodes.every(n=>[n.x,n.y,n.vx,n.vy].every(Number.isFinite)),'膠合受力必須保持數值穩定');
const glueEdit=B.clone(parallel);
assert.equal(B.moveNode(glueEdit,0,{x:6,y:2.5}),'');
assert.ok(glueEdit.bars.every((bar,i)=>Math.abs(bar.length-parallel.bars[i].length)<1e-5),'拖動膠合組合保持木材長度');
assert.ok(B.glueBars(crossing,0,1),'交叉而非並排的木材不可膠合');
run(parallel,1);
B.removeBar(parallel,0);assert.equal(parallel.joints.length,0,'刪除木材時清除依附的膠合');

const fractureJoint=B.empty();
B.addBar(fractureJoint,{x:5,y:6},{x:15,y:6});B.addBar(fractureJoint,{x:12.5,y:6},{x:12.5,y:4});
B.connectTouching(fractureJoint);
const joinedBreak=B.simulate(fractureJoint);B.cutAt(joinedBreak,0);
assert.ok(joinedBreak.bars[0].broken);
const cut=joinedBreak.fragments[0];
assert.ok(joinedBreak.constraints.filter(c=>c.kind==='pin').every(c=>c.terms.every(([i])=>i!==cut.a && i!==cut.b)),'接點隨所屬碎段移動，不跨過斷口連到另一半');
for(let i=0;i<1/B.DT;i++) B.step(joinedBreak);
assert.ok(joinedBreak.nodes.every(n=>[n.x,n.y,n.vx,n.vy].every(Number.isFinite)),'有中段接合的木材斷裂後仍保持穩定');
const many=B.empty();
for(let i=0;i<150;i++) {
  const angle=Math.PI*i/150,x=.5*Math.cos(angle),y=.5*Math.sin(angle);
  assert.equal(B.addBar(many,{x:12-x,y:4-y},{x:12+x,y:4+y}),'');
}
assert.equal(B.connectTouching(many,{x:12,y:4},.1),149,'同點相連的木材不用兩兩重複約束');
const crowded=B.simulate(many);crowded.nodes[0].vy=-1;
for(let i=0;i<.1/B.DT;i++) B.step(crowded);
assert.ok(crowded.nodes.every(n=>Math.hypot(n.vx,n.vy)<12),'多桿同點接合的速度應接近自由落體，不因冗餘約束爆升');
B.removeBar(many,75);
assert.equal(B.connectTouching(many,{x:12,y:4},.1),0,'刪除接點內其中一條木桿後，其餘木桿仍相連');
assert.equal(many.joints.length,148);
const arbitrary=B.empty();B.addBar(arbitrary,{x:5,y:6},{x:15,y:6});
const loadIndex=B.placeLoad(arbitrary,null,0,.273,2);
assert.equal(arbitrary.nodes[loadIndex].x,7.73,'負重位置不吸附至端點或方格');
assert.equal(arbitrary.bars.length,1,'中段掛重物不把原木桿切開');
assert.equal(B.totalLength(arbitrary),1,'掛重物不改變木材用量');
assert.equal(B.placeLoad(arbitrary,null,0,.273,3),loadIndex,'同一位置可調整重量而不重複建立');
assert.equal(B.placeLoad(arbitrary,null,0,0,1),arbitrary.bars[0].a,'端點負重沿用原端點');
const loadedAnywhere=B.simulate(arbitrary), hanger=loadedAnywhere.nodes[loadIndex];
hanger.y+=.01;B.step(loadedAnywhere);
const wood=loadedAnywhere.bars[0];
assert.ok(B.distance(hanger,B.barPoint(loadedAnywhere,0,.273))<1e-5,'中段重物應貼在指定材料位置，透過該處向木桿傳力');
assert.equal(B.moveNode(arbitrary,wood.b,{x:14.5,y:6}),'');
assert.ok(B.distance(arbitrary.nodes[loadIndex],B.barPoint(arbitrary,0,.273))<1e-10,'修改木桿時中段負重跟隨');
run(arbitrary,1);
B.addBar(arbitrary,{x:6,y:4},{x:10,y:4});
const retained=B.placeLoad(arbitrary,null,1,.6,2);
B.removeBar(arbitrary,0);
assert.equal(arbitrary.nodes.find(n=>n.attachment)?.attachment.bar,0,'移除前方木桿後更新負重的木桿索引');
assert.equal(arbitrary.nodes.filter(n=>n.attachment).length,1,'移除木桿也移除依附重物');
assert.ok(retained>=0);run(arbitrary,.1);

const addAfterBreak=B.empty();B.addBar(addAfterBreak,{x:5,y:6},{x:15,y:6});
const brokenLoadSim=B.simulate(addAfterBreak);B.cutAt(brokenLoadSim,0);
const rightPoint=B.barPoint(brokenLoadSim,0,.75),hit=B.barHit(brokenLoadSim,rightPoint,.01);
assert.ok(hit && Math.abs(hit.t-.75)<1e-8,'碎段命中要還原到原木桿的材料位置');
const leftTipBefore=brokenLoadSim.fragments[0].b;
const debrisLoad=B.placeLoad(addAfterBreak,brokenLoadSim,hit.bar,hit.t,2);
assert.equal(debrisLoad,2);
assert.equal(brokenLoadSim.fragments[0].b,leftTipBefore+1,'在碎段存在時新增負重也正確搬移節點索引');
assert.ok(brokenLoadSim.constraints.filter(c=>c.loadNode===debrisLoad).every(c=>c.terms.every(([i])=>!brokenLoadSim.fragments[0].path.includes(i))),'右側碎段的重物不能連回左半段');
for(let i=0;i<.2/B.DT;i++) B.step(brokenLoadSim);
assert.ok(brokenLoadSim.nodes.every(n=>[n.x,n.y,n.vx,n.vy].every(Number.isFinite)),'碎裂後新增中段負重保持穩定');
addAfterBreak.nodes[debrisLoad].load=0;brokenLoadSim.nodes[debrisLoad].load=0;
assert.equal(B.placeLoad(addAfterBreak,brokenLoadSim,0,.2,1),debrisLoad,'卸下的負重位置可供新位置重用');
assert.equal(addAfterBreak.nodes[debrisLoad].attachment.t,.2);
assert.ok(brokenLoadSim.constraints.filter(c=>c.loadNode===debrisLoad).every(c=>c.terms.every(([i])=>!brokenLoadSim.fragments[1].path.includes(i))),'重用負重位置後重新連接至正確碎段');
const splitWeights=B.empty();B.addBar(splitWeights,{x:5,y:6},{x:15,y:6});
const leftCutLoad=B.placeLoad(splitWeights,null,0,.5,1),splitSim=B.simulate(splitWeights);
B.cutAt(splitSim,0);
const rightCutLoad=B.placeLoad(splitWeights,splitSim,0,.5+1e-9,2);
assert.notEqual(rightCutLoad,leftCutLoad,'斷口兩側的位置不可合併成同一負重');
assert.equal(splitWeights.nodes[leftCutLoad].load,1,'新增另一側重物不改寫原有重量');

const touching=B.empty();B.addBar(touching,{x:7,y:8},{x:17,y:8});B.addBar(touching,{x:7,y:7.5},{x:17,y:7.5});
const beforeTouch=B.clone(touching), onUpper=B.placeLoad(touching,null,1,.4,1);
assert.equal(B.glueBars(touching,1,0),'');
assert.equal(touching.nodes[0].y,8,'接地木桿保持原位');
assert.ok(Math.abs(touching.nodes[2].y-(8-B.WOOD_WIDTH))<1e-8,'木材表面貼合，中心距離等於木材寬度');
assert.ok(B.distance(touching.nodes[onUpper],B.barPoint(touching,1,.4))<1e-8,'重物跟隨靠攏的木桿');
assert.equal(B.totalLength(touching),B.totalLength(beforeTouch),'靠攏膠合不改變木材總長度');
const reversed=B.empty();B.addBar(reversed,{x:6,y:3},{x:10,y:3});B.addBar(reversed,{x:11,y:3.5},{x:7,y:3.5});
assert.equal(B.glueBars(reversed,0,1),'','方向相反的平行木桿也能貼合');
assert.ok(Math.abs(B.barPoint(reversed,1,.5).y-3-B.WOOD_WIDTH)<1e-8);
const blocked=B.empty();B.addBar(blocked,{x:4,y:4},{x:4,y:8});B.addBar(blocked,{x:4,y:5},{x:4,y:7});
const blockedBefore=JSON.stringify(blocked);
assert.ok(B.glueBars(blocked,0,1),'靠攏會超出邊界時取消整個操作');
assert.equal(JSON.stringify(blocked),blockedBefore,'無法貼合時不留下半套幾何或膠合');
const beam=B.empty();B.addBar(beam,{x:7,y:8},{x:17,y:8});
const beamLoad=B.placeLoad(beam,null,0,.5,.02),beamDesign=JSON.stringify(beam);
const bent=run(beam,3),midpoint=B.barPoint(bent,0,.5);
assert.equal(bent.firstBreak,null,'正常負重下應先有可觀察的彎曲');
assert.ok(midpoint.y>(bent.nodes[0].y+bent.nodes[1].y)/2+.03,'木桿中段須自行下彎，不能只把負重分給兩端');
assert.ok(B.distance(bent.nodes[beamLoad],midpoint)<.01,'中段重物跟隨真正彎曲位置');
const curveHit=B.barHit(bent,B.barPoint(bent,0,.37),.01);
assert.ok(curveHit && Math.abs(curveHit.t-.37)<1e-6,'彎曲桿身的任意位置仍可命中');
const bentCenter=B.loadHit(bent,{x:B.CENTER_X,y:midpoint.y},.01);
assert.ok(bentCenter && Math.abs(B.barPoint(bent,bentCenter.bar,bentCenter.t).x-B.CENTER_X)<1e-8,'變形後新增負重仍使用目前曲線與中央線的交點');
assert.equal(B.totalLength(bent),1,'內部細分不增加木材用量或對外木桿數');
assert.equal(bent.bars.length,1);
assert.equal(JSON.stringify(beam),beamDesign,'彎曲測試不改寫原橋形');
const reinforced=B.clone(beam);
assert.equal(B.reinforce(reinforced,0),'');
assert.equal(reinforced.bars.length,2);
assert.equal(B.totalLength(reinforced),2,'加固扣除一整條木桿用量');
assert.equal(reinforced.nodes.reduce((sum,n)=>sum+n.load,0),.02,'加固不複製重物');
assert.equal(reinforced.nodes[0].y,8,'加固不能移動接地木桿');
assert.equal(reinforced.joints.filter(j=>j.kind==='glue').length,1);
const layered=run(reinforced,3);
assert.equal(layered.firstBreak,null);
assert.ok(B.barPoint(layered,0,.5).y<midpoint.y-.03,'相同負重下加固木桿下彎較少');
assert.ok(B.barPoint(layered,0,.5).y>8.005,'加固後仍會彎曲，不能變成剛體');
for(let i=0;i<=8;i++) assert.ok(Math.abs(B.distance(B.barPoint(layered,0,i/8),B.barPoint(layered,1,i/8))-B.WOOD_WIDTH)<.015,'受力後膠合木桿仍貼合');
assert.equal(B.reinforce(reinforced,0),'','同一條木桿可繼續向外加固');
assert.equal(B.totalLength(reinforced),3);
const sloped=B.empty();B.addBar(sloped,{x:7,y:8},{x:12,y:4});
assert.equal(B.reinforce(sloped,0),'','斜木桿也能加固');
assert.ok(Math.abs(B.distance(B.barPoint(sloped,0,.5),B.barPoint(sloped,1,.5))-B.WOOD_WIDTH)<1e-6);
const noSpace=B.empty();B.addBar(noSpace,{x:4,y:1},{x:7,y:1});
assert.equal(B.reinforce(noSpace,0),'','上方無空間時使用另一側');
const budget=B.clone(stock);
while(B.totalLength(budget)<19.99) assert.equal(B.reinforce(budget,budget.bars.length-1),'');
const budgetBefore=JSON.stringify(budget);
assert.ok(B.reinforce(budget,0),'剩餘木材不足時拒絕加固');
assert.equal(JSON.stringify(budget),budgetBefore,'加固失敗不留下木桿或膠合');
const unstable=B.clone(beam);unstable.nodes[beamLoad].load=20;
const failedBeam=run(unstable,1);
assert.ok(failedBeam.firstBreak || failedBeam.nodes[beamLoad].y>B.GROUND+1,'重載木桿應斷裂或先失去岸邊支承而掉落');

// 兩條木桿同時折斷時，膠水不能在同一斷口上憑空搭橋。
const pair=B.clone(beam);B.reinforce(pair,0);pair.nodes[beamLoad].load=0;
const cutPair=B.simulate(pair);
B.cutAt(cutPair,0);B.cutAt(cutPair,1);
assert.ok(cutPair.bars.every(timber=>timber.broken));
const leftSide=new Set(cutPair.fragments.filter((_,i)=>i%2===0).flatMap(p=>p.path));
const rightSide=new Set(cutPair.fragments.filter((_,i)=>i%2===1).flatMap(p=>p.path));
for(const c of cutPair.constraints) {
  const indices=c.gradients.map(g=>g.i);
  assert.ok(!(indices.some(i=>leftSide.has(i)) && indices.some(i=>rightSide.has(i))),'同位置的兩個斷口不能被膠水重新連接');
}
const offsetCutDesign=B.clone(pair);offsetCutDesign.nodes.forEach(n=>n.y-=2);
const offsetCut=B.simulate(offsetCutDesign);B.cutAt(offsetCut,0,.3);
for(let i=0;i<.1/B.DT;i++) B.step(offsetCut);
assert.ok(offsetCut.bars[1].stress<1e-4,'單層在非中央切斷後，右碎段的反向儲存不能使膠合面翻轉並產生假應力');
for(const t of [.1,.299,.301,.7,.99]) {
  assert.ok(Math.abs(B.distance(B.barPoint(offsetCut,0,t),B.barPoint(offsetCut,1,t))-B.WOOD_WIDTH)<1e-5,'非中央斷口兩側仍跟隨未斷的膠合木材');
  const hit=B.barHit(offsetCut,B.barPoint(offsetCut,0,t),.001);
  assert.ok(hit && hit.bar===0 && Math.abs(hit.t-t)<1e-6,'任意斷裂位置的碎段命中保持原材料座標');
}
const debrisCenter=B.loadHit(offsetCut,{x:B.CENTER_X,y:B.barPoint(offsetCut,0,.5).y},.001);
assert.ok(debrisCenter && Math.abs(B.barPoint(offsetCut,debrisCenter.bar,debrisCenter.t).x-B.CENTER_X)<1e-8,'碎段上的負重也只能選取中央交點');
const edgeBeam=B.empty();B.addBar(edgeBeam,{x:B.LEFT_EDGE,y:B.GROUND},{x:B.RIGHT_EDGE,y:B.GROUND});
const edgeFirst=B.simulate(edgeBeam);B.step(edgeFirst);
assert.ok(Math.abs(Math.abs(edgeFirst.nodes[0].frictionPrevious/edgeFirst.nodes[0].normalPrevious)-.6)<1e-5,'無搭岸長度的橋腳先達到摩擦上限，才可滑離邊緣');
const grip=new Function(testSource.replace('GROUND_FRICTION = 0.6','GROUND_FRICTION = 100')+';return Bridge;')();
const gripping=grip.simulate(edgeBeam);
for(let i=0;i<3;i++) grip.step(gripping);
assert.equal(gripping.nodes[0].x,B.LEFT_EDGE,'足夠靜摩擦時，岸邊節點不能因浮點殘差脫離');
assert.equal(gripping.nodes[1].x,B.RIGHT_EDGE);
const edgeResting=run(edgeBeam,3);
assert.equal(edgeResting.firstBreak,null,'正好位於岸邊的木桿不能因預測微小位移而自發斷裂');
assert.ok(edgeResting.nodes.slice(0,2).every(n=>n.y>=B.GROUND-1e-6),'沒有搭岸長度的木桿可以因自重收縮滑落，不能隱藏固定支點');
const wall=B.simulate({nodes:[{x:B.LEFT_EDGE+.01,y:9,load:0},{x:B.RIGHT_EDGE-.01,y:9,load:0}],bars:[],joints:[]});
wall.nodes.forEach(n=>n.baseMass=.01);
wall.nodes[0].vx=-100;wall.nodes[1].vx=100;B.step(wall,.01);
assert.ok(wall.nodes.every(n=>n.x>B.LEFT_EDGE && n.x<B.RIGHT_EDGE && n.y>9),'岸面以下撞岸壁不能瞬間抬升到岸上');
assert.ok(wall.nodes.every(n=>n.vx===0),'岸壁承受碰撞的水平衝量');
B.placeLoad(edgeBeam,null,0,.5,2);
const slippingEdge=B.simulate(edgeBeam);let edgeSpeed=0;
for(let i=0;i<3/B.DT;i++) {B.step(slippingEdge);for(const n of slippingEdge.nodes) edgeSpeed=Math.max(edgeSpeed,Math.hypot(n.vx,n.vy));}
assert.ok(edgeSpeed<100,'滑落後的岸壁碰撞不能注入能量而把木桿彈飛');
assert.ok(slippingEdge.nodes[0].y>B.GROUND,'有足夠水平拉力時岸邊支承仍能滑落，不是固定支點');
console.log('通過：中央線放置負重、加固、受力彎曲與折斷、20 m 用量、接合／膠合、編輯刪除及 95 cm 河口回歸測試。');
